deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

apisix:
  node_listen:
    - ip: ${{APISIX_LISTEN_ADDRESS:=0.0.0.0}}
      port: 9080
  ssl:
    enable: false
  enable_admin: false
  trusted_addresses:
    - 127.0.0.1

plugins:
  - app-auth
  - openid-connect
  - proxy-rewrite
  - real-ip
  - cors
  - prometheus
