---
- name: Install Docker
  hosts: docker_hosts
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure dependencies are installed
      package:
        name:
          - bc
          - curl
          - expect
          - git
          - ca-certificates
        state: present

    - name: Add Docker repository to apt
      deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        suites: "{{ ansible_facts['distribution_release'] }}"
        components: stable
        architectures: >-
          {{ {'x86_64': 'amd64', 'aarch64': 'arm64'}.get(
            ansible_facts.architecture, ansible_facts.architecture) }}
        signed_by: https://download.docker.com/linux/ubuntu/gpg
        install_python_debian: true
        state: present
        enabled: yes

    - name: Update apt cache with repo
      apt:
        update_cache: yes

    - name: Install Docker and Compose
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker service is enabled and started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
