---

all:
  children:
    docker_hosts:
      hosts:
        azure-compose:
          ansible_host: azure-compose

    frontend_vm:
      hosts:
        azure-frontend:
          ansible_host: frontend
    backend_vm:
      hosts:
        azure-backend:
          ansible_host: backend
